horizontalsystems/ethereum-kit-ios

- HSEthereumKit/HSEthereumKit/Core/EthereumKit.swift
> Update only new transactions #4

- HSEthereumKit/HSEthereumKit/Core/EthereumKit.swift
- HSEthereumKitDemo/HSEthereumKitDemo/BalanceController.swift
- HSEthereumKitDemo/HSEthereumKitDemo/TransactionsController.swift
> Refactor EthereumKit api (#24)

- HSEthereumKit/HSEthereumKit.xcodeproj/project.pbxproj
- HSEthereumKit/HSEthereumKit/Core/Erc20Holder.swift
- HSEthereumKit/HSEthereumKit/Core/EthereumKit.swift
- HSEthereumKit/HSEthereumKit/Core/GethProvider.swift
- HSEthereumKit/HSEthereumKit/Core/Protocols.swift
- HSEthereumKit/HSEthereumKit/EthereumKit/Helper/EIP55.swift
- HSEthereumKit/HSEthereumKit/EthereumKit/Networking/Geth.swift
- HSEthereumKit/HSEthereumKit/EthereumKit/Networking/Request/Etherscan.swift
- HSEthereumKit/HSEthereumKitTests/Helpers/EIP55Tests.swift
- HSEthereumKitDemo/HSEthereumKitDemo/BalanceController.swift
- Merge refresh transactions
- Remove timers for tokens
- Increase refresh time to 60 seconds
- Fix EIP55 format method
Closes #33
> Remove separate update transaction.

- HSEthereumKit/HSEthereumKit.xcodeproj/project.pbxproj
- HSEthereumKit/HSEthereumKit/Core/Extensions.swift
- HSEthereumKit/HSEthereumKit/EthereumKit/Helper/RLPElement.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/Connection/Connection.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/DevP2P/DevP2PConnection.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/LESPeer.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/MaxCost.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/BlockBodiesMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/BlockHeadersMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/ContractCodesMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/HelperTrieProofsMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/ProofsMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/ReceiptsMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/StatusMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/TransactionStatusMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/PeerGroup.swift
- HSEthereumKit/HSEthereumKitTests/Spv/Net/DevP2P/CapabilityHelperTests.swift
- fix parsing signed Int values from RLP
- change all BV (Buffer Value) variable types from BInt to Int
> Parse flow control variables from StatusMessage

- HSEthereumKit/HSEthereumKit/Spv/Core/SpvProtocols.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/LESPeer.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/GetBlockHeadersMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/PeerGroup.swift
- HSEthereumKit/HSEthereumKitTests/Extensions.swift
- HSEthereumKit/HSEthereumKitTests/Spv/Net/LES/LESPeerTests.swift
> Handle announced block headers in PeerGroup

- HSEthereumKit/HSEthereumKit.xcodeproj/project.pbxproj
- HSEthereumKit/HSEthereumKit/Core/ApiBlockchain.swift
- HSEthereumKit/HSEthereumKit/Core/EthereumKit.swift
- HSEthereumKit/HSEthereumKit/Core/Protocols.swift
- HSEthereumKit/HSEthereumKit/EthereumKit/Model/RawTransaction.swift
- HSEthereumKit/HSEthereumKit/Spv/Core/SpvBlockchain.swift
- HSEthereumKit/HSEthereumKit/Spv/Core/SpvGrdbStorage.swift
- HSEthereumKit/HSEthereumKit/Spv/Core/SpvProtocols.swift
- HSEthereumKit/HSEthereumKit/Spv/Core/TransactionSigner.swift
- HSEthereumKit/HSEthereumKit/Spv/Models/AccountState.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/LESPeer.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/GetTransactionStatusMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/SendTransactionMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Messages/TransactionStatusMessage.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/LES/Requests/AccountStateRequest.swift
- HSEthereumKit/HSEthereumKit/Spv/Net/PeerGroup.swift
- HSEthereumKit/HSEthereumKitTests/Core/EthereumKitTests.swift
- HSEthereumKit/HSEthereumKitTests/Extensions.swift
- HSEthereumKit/HSEthereumKitTests/Spv/Net/LES/LESPeerTests.swift
- HSEthereumKit/HSEthereumKitTests/Spv/Net/PeerGroupTests.swift
- extract storage from EthereumKit and delegate it to IBlockchain
- create TransactionSigner for signing transactions for SPV blockchain
- implement send transaction function in SPV blockchain
- store AccountState in database
- implement send transactions and transaction status related devp2p messages
> Implement send transaction in SPV blockchain (#78)

- HSEthereumKit/HSEthereumKit/Core/EthereumKit.swift
- HSEthereumKitDemo/HSEthereumKitDemo/Core/Manager.swift
> Add ability to create EthereumKit instance with mnemonic words

- HSEthereumKit.podspec
- HSEthereumKit/HSEthereumKit.xcodeproj/project.pbxproj
- HSEthereumKit/HSEthereumKit/Core/ApiBlockchain.swift
- HSEthereumKit/HSEthereumKit/Core/EthereumKit.swift
- HSEthereumKitDemo/HSEthereumKitDemo.xcodeproj/project.pbxproj
- HSEthereumKitDemo/HSEthereumKitDemo/Core/Erc20Adapter.swift
- HSEthereumKitDemo/HSEthereumKitDemo/Core/EthereumAdapter.swift
- Podfile
- Podfile.lock
> No fee inside

- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
- Erc20Kit/Erc20Kit/Core/Protocols.swift
- Erc20Kit/Erc20Kit/Core/TokenHolder.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Managers/NetworkManager.swift
- unregister token for Erc20Kit
- fee for Erc20Kit
- remove delegate for EthereumKit
- public NetworkError class in EthereumKit
#85
> Add missing public methods for Erc20Kit and EthereumKit

- Erc20Kit/Erc20Kit/Core/DataProvider.swift
- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
- Erc20Kit/Erc20Kit/Core/Protocols.swift
- Erc20Kit/Erc20Kit/Core/TokenHolder.swift
- Erc20Kit/Erc20Kit/Core/TransactionManager.swift
- EthereumKit/EthereumKit/Api/Core/ApiBlockchain.swift
- EthereumKit/EthereumKit/Api/Core/InfuraApiProvider.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Core/Signal.swift
- EthereumKitDemo/EthereumKitDemo/Adapters/Erc20Adapter.swift
- EthereumKitDemo/EthereumKitDemo/Adapters/EthereumAdapter.swift
- EthereumKitDemo/EthereumKitDemo/Adapters/IAdapter.swift
- EthereumKitDemo/EthereumKitDemo/Configuration.swift
- EthereumKitDemo/EthereumKitDemo/Controllers/BalanceController.swift
- EthereumKitDemo/EthereumKitDemo/Controllers/TransactionsController.swift
> Send fixes

- EthereumKit/EthereumKit.xcodeproj/project.pbxproj
- EthereumKit/EthereumKit/Api/Core/ApiBlockchain.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Spv/Net/MainNet.swift
- EthereumKitDemo/EthereumKitDemo/Configuration.swift
> Add mainnet support

- EthereumKit/EthereumKit/Api/Core/InfuraApiProvider.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Helper/RLP.swift
- EthereumKit/EthereumKit/Helper/RLPElement.swift
- EthereumKit/EthereumKit/Models/Block.swift
- EthereumKit/EthereumKit/Spv/Core/SpvBlockchain.swift
- EthereumKit/EthereumKit/Spv/Core/SpvProtocols.swift
- EthereumKit/EthereumKit/Spv/Models/BlockHeader.swift
- EthereumKit/EthereumKit/Spv/Net/LES/Messages/AnnounceMessage.swift
- EthereumKit/EthereumKit/Spv/Net/LES/Messages/StatusMessage.swift
- EthereumKit/EthereumKit/Spv/Net/LES/Requests/AccountStateRequest.swift
- EthereumKit/EthereumKit/Spv/Net/MainNet.swift
- EthereumKit/EthereumKit/Spv/Net/PeerGroup.swift
- EthereumKit/EthereumKit/Spv/Net/Ropsten.swift
- EthereumKit/EthereumKitTests/Extensions.swift
- EthereumKit/EthereumKitTests/Spv/Net/LES/LESPeerTests.swift
- EthereumKit/EthereumKitTests/Spv/Net/PeerGroupTests.swift
- EthereumKitDemo/EthereumKitDemo/Core/Manager.swift
- fix chainId for MainNet network
Closes #106
> Integrate RPC provider into SPV blockchain

- Erc20Kit/Erc20Kit/Core/BalanceManager.swift
- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
- Erc20Kit/Erc20Kit/Core/GrdbStorage.swift
- Erc20Kit/Erc20Kit/Core/Protocols.swift
- Erc20Kit/Erc20Kit/Core/TransactionManager.swift
- EthereumKit/EthereumKit/Api/Core/ApiBlockchain.swift
- EthereumKit/EthereumKit/Api/Core/ApiGrdbStorage.swift
- EthereumKit/EthereumKit/Core/BaseGrdbStorage.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Core/EthereumKitState.swift
- EthereumKit/EthereumKit/Core/Protocols.swift
- EthereumKit/EthereumKit/Spv/Core/SpvBlockchain.swift
- EthereumKit/EthereumKit/Spv/Core/SpvGrdbStorage.swift
- EthereumKitDemo/EthereumKitDemo/Adapters/Erc20Adapter.swift
- EthereumKitDemo/EthereumKitDemo/Configuration.swift
- EthereumKitDemo/EthereumKitDemo/Core/Manager.swift
- fix memory leak in TransactionManager
- remove all "clear" methods from kits
Closes #109
> Static methods for deleting database files (#109)

- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
> For Erc20Kit always sync balance first and then transactions (#111)

- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
- use estimate gas limit for fee calculations (100k)
> Increase gas limit for Erc20 to 150k (#113)

- EthereumKit/EthereumKit/Api/Core/InfuraApiProvider.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Managers/NetworkManager.swift
- EthereumKitDemo/EthereumKitDemo/Configuration.swift
- EthereumKitDemo/EthereumKitDemo/Core/Manager.swift
> Add ability to use project secret for Infura using basic auth (#117)

- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
- EthereumKit/EthereumKit.xcodeproj/project.pbxproj
- Podfile.lock
- remove separate "estimateGasLimit" and "gasLimit" hard-coded constants
> Erc20Kit: add ability to set custom gas limit in constructor

- EthereumKit/EthereumKit/Api/Core/ApiBlockchain.swift
- EthereumKit/EthereumKit/Api/Core/ApiProtocols.swift
- EthereumKit/EthereumKit/Api/Core/InfuraApiProvider.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Core/EtherscanApiProvider.swift
- EthereumKit/EthereumKit/Core/Protocols.swift
- EthereumKit/EthereumKit/Core/TransactionManager.swift
- EthereumKit/EthereumKit/Spv/Core/SpvBlockchain.swift
- add protocol ITransactionManager
- add field 'source' to IBlockchain, ITransacitionProvider protocols
ref #1111
> Add statusInfo() method to EthereumKit

- EthereumKit/EthereumKit/Core/EthereumKit.swift
> Fix strings

- Erc20Kit.swift.podspec
- Erc20Kit/Erc20Kit.xcodeproj/project.pbxproj
- Erc20Kit/Erc20Kit/Core/DataProvider.swift
- Erc20Kit/Erc20Kit/Core/Erc20Kit.swift
- Erc20Kit/Erc20Kit/Core/Protocols.swift
- Erc20Kit/Erc20Kit/Core/TransactionBuilder.swift
- Erc20Kit/Erc20Kit/Core/TransactionManager.swift
- Erc20Kit/Erc20Kit/Info.plist
- EthereumKit.swift.podspec
- EthereumKit/EthereumKit.xcodeproj/project.pbxproj
- EthereumKit/EthereumKit/Api/Core/ApiBlockchain.swift
- EthereumKit/EthereumKit/Api/Core/ApiProtocols.swift
- EthereumKit/EthereumKit/Api/Core/InfuraApiProvider.swift
- EthereumKit/EthereumKit/Core/EthereumKit.swift
- EthereumKit/EthereumKit/Core/Extensions.swift
- EthereumKit/EthereumKit/Core/Protocols.swift
- EthereumKit/EthereumKit/Core/TransactionBuilder.swift
- EthereumKit/EthereumKit/Info.plist
- EthereumKit/EthereumKit/Spv/Core/SpvBlockchain.swift
- EthereumKitDemo/EthereumKitDemo.xcodeproj/project.pbxproj
- EthereumKitDemo/EthereumKitDemo/Adapters/Erc20Adapter.swift
- EthereumKitDemo/EthereumKitDemo/Adapters/EthereumAdapter.swift
- EthereumKitDemo/EthereumKitDemo/Adapters/IAdapter.swift
- EthereumKitDemo/EthereumKitDemo/Controllers/SendController.swift
- EthereumKitDemo/EthereumKitDemo/Controllers/SendController.xib
- EthereumKitDemo/EthereumKitDemo/Info.plist
Change kit's interface.
ref #136
> Implement estimated gas api request for erc20 tokens. 

- EthereumKit/EthereumKit.xcodeproj/project.pbxproj
- EthereumKit/EthereumKit/Api/Core/InfuraApiProvider.swift
- EthereumKit/EthereumKit/Models/InfuraGasLimitResponse.swift
> Handle infura error when try get gasLimit to invalid transaction

- Erc20Kit/Erc20Kit/Core/TransactionManager.swift
- Make serial scheduler for sync erc20.
ref #145
> remove secondary log with same txHash and zero value.

- Erc20Kit/Classes/Core/EtherscanTransactionProvider.swift
- Erc20Kit/Classes/Core/GrdbStorage.swift
- Erc20Kit/Classes/Core/Kit.swift
- Erc20Kit/Classes/Core/Protocols.swift
- Erc20Kit/Classes/Core/TransactionManager.swift
- Erc20Kit/Classes/Core/TransactionProvider.swift
- Erc20Kit/Classes/Models/Transaction.swift
- EthereumKit/Classes/Api/Core/InfuraApiProvider.swift
- EthereumKit/Classes/Core/EtherscanApiProvider.swift
- EthereumKit/Classes/Core/Kit.swift
- EthereumKit/Classes/Models/RpcApi.swift
- Example/EthereumKit/Core/Manager.swift
Prepare for Incubed intergration
> Refactor transactions fetching

- EthereumKit/Classes/Core/EtherscanApiProvider.swift
- EthereumKit/Classes/Managers/NetworkManager.swift
- do not pass Alamofire errors outside of NetworkManager
- use protocol with associated type for mapper
> NetworkManager improvements

- Erc20Kit/Classes/Core/Kit.swift
- EthereumKit/Classes/Core/Kit.swift
- if no address - fallback to default gas limit of 21000
- if no amount - use default minimum amount
> Add ability to estimate gas without address and amount

- EthereumKit/Classes/Core/Kit.swift
to_hex_string is public in data.extension
> Revert last commit

- Erc20Kit/Classes/Core/TransactionManager.swift
- EthereumKit/Classes/Incubed/In3Private.h
- EthereumKit/Classes/Incubed/In3Private.m
- EthereumKit/Classes/Incubed/IncubedRpcApiProvider.swift
- do not count 'not found' as failed transaction
- add not found state to incubed provider
> Fix failing of pending transactions

- Erc20Kit/Classes/Core/Kit.swift
- Erc20Kit/Classes/Core/Protocols.swift
- Erc20Kit/Classes/Core/TransactionManager.swift
- EthereumKit/Classes/Api/Core/ApiProtocols.swift
- EthereumKit/Classes/Api/Core/RpcBlockchain.swift
- EthereumKit/Classes/Api/Core/WebSocketRpcSyncer.swift
- EthereumKit/Classes/Api/JsonRpc/EstimateGasJsonRpc.swift
- EthereumKit/Classes/Core/EthereumKitState.swift
- EthereumKit/Classes/Core/Kit.swift
- EthereumKit/Classes/Core/Protocols.swift
- EthereumKit/Classes/Core/TransactionManager.swift
- EthereumKit/Classes/Spv/Core/SpvBlockchain.swift
> Refresh Ethereum/Erc20 transactions when balance and/or nonce is updated

- CHANGELOG.md
- Erc20Kit.swift.podspec
- EthereumKit.swift.podspec
- Example/Podfile.lock
> Update pod versions

- CHANGELOG.md
- EthereumKit/Classes/Core/Kit.swift
- Example/EthereumKit/Configuration.swift
- Example/EthereumKit/Core/Manager.swift
- UniswapKit/Classes/Kit.swift
- UniswapKit/Classes/Models/Pair.swift
- UniswapKit/Classes/TokenFactory.swift
- UniswapKit/Classes/TradeManager.swift
- Increase maxGasLimit to 2000000
> Integrate PancakeSwap to UniswapKit

- OneInchKit/Classes/Kit.swift
- OneInchKit/Classes/OneInchProvider.swift
- UniswapKit/Classes/Decorations/SwapMethodDecoration.swift
Make init swapDecoration's public.
> Add handling oneInch fee error.

- OneInchKit/Classes/OneInchProvider.swift
Add "Not enough ETH balance" to handled errors
> Handle one new oneInch error

- EthereumKit/Classes/Core/EIP1155/Eip1155Provider.swift
- EthereumKit/Classes/Core/Kit.swift
> Add 'get balance' for eip1155 tokens.

- EthereumKit/Classes/Contracts/ContractMethodHelper.swift
- EthereumKit/Classes/Core/Extensions.swift
- EthereumKit/Classes/Core/L2Fee/L1FeeProvider.swift
- EthereumKit/Classes/Core/TransactionBuilder.swift
Fix encoding data field in contract method.
> Add l1 fee provider. Extend transaction encoding to static method. 

- EthereumKit.swift.podspec
- EthereumKit/Classes/Api/Core/Transforms.swift
- EthereumKit/Classes/Core/EtherscanTransactionProvider.swift
- EthereumKit/Classes/Core/Kit.swift
- EthereumKit/Classes/Core/Protocols.swift
- EthereumKit/Classes/Eip20/Eip20Storage.swift
- EthereumKit/Classes/Models/ProviderEip1155Transaction.swift
- EthereumKit/Classes/Models/ProviderEip721Transaction.swift
- EthereumKit/Classes/Models/ProviderInternalTransaction.swift
- EthereumKit/Classes/Models/ProviderTransaction.swift
- Example/EthereumKit.xcodeproj/project.pbxproj
- Example/EthereumKit/Core/Manager.swift
- Example/Podfile
- Example/Podfile.lock
- NftKit.swift.podspec
- NftKit/Classes/Core/Eip1155TransactionSyncer.swift
- NftKit/Classes/Core/Eip721TransactionSyncer.swift
- NftKit/Classes/Core/Kit.swift
- NftKit/Classes/Core/Storage.swift
- NftKit/Classes/Models/Eip1155Event.swift
- NftKit/Classes/Models/Eip721Event.swift
- add transactions syncers and event models (with storage)
- refactor `EthereumKit` provider transactions mapping to use `ObjectMapper`
> Create initial structure for `NftKit`
